# Generated by Django 5.1.4 on 2026-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
