# Generated by Django 5.1.4 on 2026-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_contact_number_event_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
