# Generated by Django 5.1.4 on 2026-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_sponsor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
