# Generated by Django 5.1.4 on 2026-01-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_agendaitem_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={},
        ),
    ]
