# Generated by Django 5.1.4 on 2026-01-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, null=True, upload_to='event_files/'),
        ),
    ]
