# Generated by Django 5.1.4 on 2026-01-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_event_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
