# Generated by Django 5.1.4 on 2026-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventorganizer_event_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
