# Generated by Django 5.1.4 on 2026-01-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
