# Generated by Django 5.1.4 on 2025-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshi_quality_standard', '0004_alter_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
