# Generated by Django 5.1.4 on 2025-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshi_quality_standard', '0007_response_earned_points_delete_savedanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
