# Generated by Django 5.1.4 on 2025-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshi_quality_standard', '0009_response_category_response_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
