# Generated by Django 5.1.4 on 2026-01-30 04:59

import django.db.models.deletion
import jobbriz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeshipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organisation', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'ordering': ['issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_or_qualification', models.CharField(choices=[('General Literate', 'General Literate'), ('Below SLC', 'Below SLC'), ('+2', '+2'), ('Bachelors', 'Bachelors'), ('Master & above', 'Master & above'), ('Pre-Diploma', 'Pre-Diploma'), ('Diploma', 'Diploma'), ('TLSC', 'TLSC'), ('No Education', 'No Education')], max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('year_of_completion', models.DateField(blank=True, null=True)),
                ('course_highlights', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year_of_completion'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_registration_certificate', models.FileField(blank=True, null=True, upload_to='company_registration_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbriz.industry')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Apprenticeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('level', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=20)),
                ('overview_of_role', models.TextField()),
                ('duration', models.CharField(choices=[('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('30 months', '30 months'), ('36 months', '36 months'), ('None', 'None')], default='None', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation_summary', models.TextField()),
                ('occupation_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeships', to='jobbriz.apprenticeshipcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeships_created', to='jobbriz.company')),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubMajorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('major_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_major_groups', to='jobbriz.majorgroup')),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MinorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_major_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_groups', to='jobbriz.submajorgroup')),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('minor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_groups', to='jobbriz.minorgroup')),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('skill_levels', models.CharField(blank=True, choices=[('RPL', 'RPL'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=200, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_salary_range_from', models.IntegerField(blank=True, default=0, null=True)),
                ('preferred_salary_range_to', models.IntegerField(blank=True, default=0, null=True)),
                ('remote_work_preference', models.BooleanField(blank=True, default=False, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('career_history', models.ManyToManyField(blank=True, related_name='job_seeker_career_history', to='jobbriz.careerhistory')),
                ('certifications', models.ManyToManyField(blank=True, related_name='job_seeker_certifications', to='jobbriz.certification')),
                ('education', models.ManyToManyField(blank=True, to='jobbriz.education')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='job_seeker_languages', to='jobbriz.language')),
                ('preferred_locations', models.ManyToManyField(blank=True, related_name='job_seeker_preferred_locations', to='jobbriz.location')),
                ('skills', models.ManyToManyField(blank=True, related_name='job_seeker_skills', to='jobbriz.skill')),
                ('preferred_unit_groups', models.ManyToManyField(blank=True, related_name='job_seeker_preferred_unit_groups', to='jobbriz.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('required_skill_level', models.CharField(choices=[('RPL', 'RPL'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=10)),
                ('required_education', models.CharField(choices=[('General Literate', 'General Literate'), ('Below SLC', 'Below SLC'), ('+2', '+2'), ('Bachelors', 'Bachelors'), ('Master & above', 'Master & above'), ('Pre-Diploma', 'Pre-Diploma'), ('Diploma', 'Diploma'), ('TLSC', 'TLSC'), ('No Education', 'No Education')], default='No Education', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('show_salary', models.BooleanField(default=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Expired', 'Expired'), ('Closed', 'Closed')], default='Published', max_length=20)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('All', 'All')], max_length=20)),
                ('views_count', models.PositiveIntegerField(blank=True, default=0)),
                ('applications_count', models.PositiveIntegerField(blank=True, default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbriz.company')),
                ('location', models.ManyToManyField(related_name='job_posts', to='jobbriz.location')),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbriz.unitgroup')),
            ],
            bases=(jobbriz.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobbriz.jobpost')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbriz.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('seeker_message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='jobbriz.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='jobbriz.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'job_seeker')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobbriz.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='jobbriz.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
