# Generated by Django 5.1.4 on 2026-02-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0007_alter_hirerequest_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenticeship',
            name='category',
        ),
        migrations.RemoveField(
            model_name='apprenticeship',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ApprenticeshipCategory',
        ),
        migrations.DeleteModel(
            name='Apprenticeship',
        ),
    ]
