# Generated by Django 5.1.4 on 2026-02-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0010_alter_jobseeker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='current_address',
            new_name='current_district',
        ),
        migrations.RenameField(
            model_name='jobseeker',
            old_name='permanent_address',
            new_name='current_municipality',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='current_province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='current_ward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='permanent_district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='permanent_municipality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='permanent_province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='permanent_ward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
