# Generated by Django 5.1.4 on 2026-02-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0011_rename_current_address_jobseeker_current_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='motivation_letter',
            new_name='motivational_letter',
        ),
    ]
