# Generated by Django 5.1.4 on 2026-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0013_alter_education_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='current_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='permanent_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='permanent_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='permanent_ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
