# Generated by Django 5.1.4 on 2026-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0014_alter_jobseeker_current_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipindustry',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
