# Generated by Django 5.1.4 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0015_internshipindustry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(help_text='District / Municipality / Ward', max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('education_level', models.CharField(choices=[('Grade 10', 'Grade 10'), ('SEE completed', 'SEE completed')], max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('year_of_see_completion', models.CharField(help_text='Year of SEE Completion', max_length=4)),
                ('trade', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automobile', 'Automobile'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('IT', 'IT'), ('Hotel Mgmt.', 'Hotel Mgmt.'), ('ECD', 'Early Childhood Development'), ('Tea Technology', 'Tea Technology')], max_length=50, verbose_name='Trade / Field Applying For')),
                ('preferred_training_provider', models.CharField(choices=[('Manamohan Memorial Polytechnic', 'Manamohan Memorial Polytechnic'), ('Kankai Polytechnic Institute', 'Kankai Polytechnic Institute'), ('Shailaja Acharya Memorial Polytechnic', 'Shailaja Acharya Memorial Polytechnic'), ('Pushpa-Dhirendra Memorial Academy', 'Pushpa-Dhirendra Memorial Academy'), ('Nara Bahadur Karmacharya Bahuprabidhik Shikshyalaya', 'Nara Bahadur Karmacharya Bahuprabidhik Shikshyalaya'), ('Aadarsha School', 'Aadarsha School'), ('Ratna Kumar Bantawa Bahuprabidhik Shikshyalaya', 'Ratna Kumar Bantawa Bahuprabidhik Shikshyalaya')], max_length=255, verbose_name='Preferred Training Provider')),
                ('industry_preference_1', models.CharField(choices=[('MM Group', 'MM Group'), ('Bagmati Oil Industries', 'Bagmati Oil Industries'), ('Kabra G Group', 'Kabra G Group'), ('Laminar Private Limited', 'Laminar Private Limited'), ('Purwanchal Lube Oil Limited (PLO)', 'Purwanchal Lube Oil Limited (PLO)'), ('Hulas Wire Industries Limited', 'Hulas Wire Industries Limited'), ('Premier Wires Pvt. Ltd.', 'Premier Wires Pvt. Ltd'), ('Fujima Oil Company Ltd.', 'Fujima Oil Company Ltd.'), ('Shivam Footwears Pvt. Ltd.', 'Shivam Footwears Pvt. Ltd.'), ('Kwality Foods Nepal', 'Kwality Foods Nepal'), ('Bhudeo Khadya Udyog Pvt. Ltd.', 'Bhudeo Khadya Udyog Pvt. Ltd.'), ('Alexa Lifesciences Pvt. Ltd.', 'Alexa Lifesciences Pvt. Ltd.'), ('Jay Shree Electrical Pvt. Ltd.', 'Jay Shree Electrical Pvt. Ltd.'), ('Kiran Cake Parlour Pvt. Ltd.', 'Kiran Cake Parlour Pvt. Ltd.'), ('Rabindra Knitfab Industries', 'Rabindra Knitfab Industries'), ('Others', 'Others')], max_length=255, verbose_name='Requested Industry (1st Preference)')),
                ('industry_preference_2', models.CharField(blank=True, choices=[('MM Group', 'MM Group'), ('Bagmati Oil Industries', 'Bagmati Oil Industries'), ('Kabra G Group', 'Kabra G Group'), ('Laminar Private Limited', 'Laminar Private Limited'), ('Purwanchal Lube Oil Limited (PLO)', 'Purwanchal Lube Oil Limited (PLO)'), ('Hulas Wire Industries Limited', 'Hulas Wire Industries Limited'), ('Premier Wires Pvt. Ltd.', 'Premier Wires Pvt. Ltd'), ('Fujima Oil Company Ltd.', 'Fujima Oil Company Ltd.'), ('Shivam Footwears Pvt. Ltd.', 'Shivam Footwears Pvt. Ltd.'), ('Kwality Foods Nepal', 'Kwality Foods Nepal'), ('Bhudeo Khadya Udyog Pvt. Ltd.', 'Bhudeo Khadya Udyog Pvt. Ltd.'), ('Alexa Lifesciences Pvt. Ltd.', 'Alexa Lifesciences Pvt. Ltd.'), ('Jay Shree Electrical Pvt. Ltd.', 'Jay Shree Electrical Pvt. Ltd.'), ('Kiran Cake Parlour Pvt. Ltd.', 'Kiran Cake Parlour Pvt. Ltd.'), ('Rabindra Knitfab Industries', 'Rabindra Knitfab Industries'), ('Others', 'Others')], max_length=255, null=True, verbose_name='Requested Industry (2nd Preference)')),
                ('industry_preference_3', models.CharField(blank=True, choices=[('MM Group', 'MM Group'), ('Bagmati Oil Industries', 'Bagmati Oil Industries'), ('Kabra G Group', 'Kabra G Group'), ('Laminar Private Limited', 'Laminar Private Limited'), ('Purwanchal Lube Oil Limited (PLO)', 'Purwanchal Lube Oil Limited (PLO)'), ('Hulas Wire Industries Limited', 'Hulas Wire Industries Limited'), ('Premier Wires Pvt. Ltd.', 'Premier Wires Pvt. Ltd'), ('Fujima Oil Company Ltd.', 'Fujima Oil Company Ltd.'), ('Shivam Footwears Pvt. Ltd.', 'Shivam Footwears Pvt. Ltd.'), ('Kwality Foods Nepal', 'Kwality Foods Nepal'), ('Bhudeo Khadya Udyog Pvt. Ltd.', 'Bhudeo Khadya Udyog Pvt. Ltd.'), ('Alexa Lifesciences Pvt. Ltd.', 'Alexa Lifesciences Pvt. Ltd.'), ('Jay Shree Electrical Pvt. Ltd.', 'Jay Shree Electrical Pvt. Ltd.'), ('Kiran Cake Parlour Pvt. Ltd.', 'Kiran Cake Parlour Pvt. Ltd.'), ('Rabindra Knitfab Industries', 'Rabindra Knitfab Industries'), ('Others', 'Others')], max_length=255, null=True, verbose_name='Requested Industry (3rd Preference)')),
                ('preferred_location', models.CharField(blank=True, choices=[('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Jhapa', 'Jhapa'), ('Ilam', 'Ilam'), ('Any', 'Any')], max_length=50, null=True)),
                ('motivation_letter', models.TextField(help_text='Why choose this industry? (150–300 words)')),
                ('citizenship', models.FileField(upload_to='apprenticeship/citizenship/')),
                ('supporting_certificates', models.FileField(blank=True, null=True, upload_to='apprenticeship/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
