# Generated by Django 5.1.4 on 2026-02-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0016_apprenticeshipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenticeshipapplication',
            name='industry_preference_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeship_pref_1', to='jobbriz.internshipindustry', verbose_name='Requested Industry (1st Preference)'),
        ),
        migrations.AlterField(
            model_name='apprenticeshipapplication',
            name='industry_preference_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeship_pref_2', to='jobbriz.internshipindustry', verbose_name='Requested Industry (2nd Preference)'),
        ),
        migrations.AlterField(
            model_name='apprenticeshipapplication',
            name='industry_preference_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeship_pref_3', to='jobbriz.internshipindustry', verbose_name='Requested Industry (3rd Preference)'),
        ),
    ]
