# Generated by Django 5.1.4 on 2026-02-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0017_alter_apprenticeshipapplication_industry_preference_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenticeshipapplication',
            name='supporting_certificates',
        ),
        migrations.AlterField(
            model_name='apprenticeshipapplication',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ApprenticeshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='apprenticeship/documents/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobbriz.apprenticeshipapplication')),
            ],
        ),
    ]
