# Generated by Django 5.1.4 on 2026-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0018_remove_apprenticeshipapplication_supporting_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenticeshipapplication',
            name='address',
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
