# Generated by Django 5.1.4 on 2026-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0019_remove_apprenticeshipapplication_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenticeshipapplication',
            name='preferred_training_provider',
            field=models.CharField(max_length=255, verbose_name='Preferred Training Provider'),
        ),
    ]
