# Generated by Django 5.1.4 on 2026-02-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0020_alter_apprenticeshipapplication_preferred_training_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(help_text='e.g. Web Developer, Electrician, Plumber', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Describe your interest and expertise')),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=15)),
                ('availability', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], default='Full Time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_locations', models.ManyToManyField(blank=True, to='jobbriz.location')),
                ('skills', models.ManyToManyField(blank=True, related_name='work_interest_profiles', to='jobbriz.skill')),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_profiles', to='jobbriz.unitgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_interest_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'unit_group')},
            },
        ),
    ]
