# Generated by Django 5.1.4 on 2026-02-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0022_workinteresthire'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipindustry',
            name='file_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipindustry',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='internship_industry_logos'),
        ),
        migrations.AlterField(
            model_name='internshipindustry',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
