# Generated by Django 5.1.4 on 2026-02-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0023_internshipindustry_file_link_internshipindustry_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipindustry',
            old_name='link',
            new_name='website_link',
        ),
    ]
