# Generated by Django 5.1.4 on 2026-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0024_rename_link_internshipindustry_website_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='preferred_locations',
        ),
        migrations.RemoveField(
            model_name='workinterest',
            name='preferred_locations',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workinterest',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
