# Generated by Django 5.1.4 on 2026-02-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0025_remove_jobpost_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinterest',
            unique_together=set(),
        ),
    ]
