# Generated by Django 5.1.4 on 2026-02-17 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0026_alter_workinterest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('current_province', models.CharField(blank=True, max_length=255, null=True)),
                ('current_district', models.CharField(blank=True, max_length=255, null=True)),
                ('current_municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('current_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supervisor_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_department', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_month', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('motivational_letter', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='internship_cvs/')),
                ('skill_levels', models.CharField(blank=True, choices=[('RPL', 'RPL'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=200, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_locations', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_salary_range_from', models.IntegerField(blank=True, default=0, null=True)),
                ('preferred_salary_range_to', models.IntegerField(blank=True, default=0, null=True)),
                ('remote_work_preference', models.BooleanField(blank=True, default=False, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Shift Based', 'Shift Based'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('career_history', models.ManyToManyField(blank=True, related_name='internship_seeker_career_history', to='jobbriz.careerhistory')),
                ('certifications', models.ManyToManyField(blank=True, related_name='internship_seeker_certifications', to='jobbriz.certification')),
                ('education', models.ManyToManyField(blank=True, to='jobbriz.education')),
                ('internship_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobbriz.internshipindustry')),
                ('languages', models.ManyToManyField(blank=True, related_name='internship_seeker_languages', to='jobbriz.language')),
                ('preferred_unit_groups', models.ManyToManyField(blank=True, related_name='internship_seeker_preferred_unit_groups', to='jobbriz.unitgroup')),
                ('skills', models.ManyToManyField(blank=True, related_name='internship_seeker_skills', to='jobbriz.skill')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
