# Generated by Django 5.1.4 on 2026-02-19 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0027_internship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('All', 'All')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range_max',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range_min',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Expired', 'Expired'), ('Closed', 'Closed')], db_index=True, default='Published', max_length=20),
        ),
        migrations.AlterField(
            model_name='workinterest',
            name='availability',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], db_index=True, default='Full Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='workinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workinterest',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='jobbriz_job_job_id_a6d260_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', '-posted_date'], name='jobbriz_job_status_3542e0_idx'),
        ),
        migrations.AddIndex(
            model_name='workinterest',
            index=models.Index(fields=['proficiency_level', 'availability', '-created_at'], name='jobbriz_wor_profici_eeb6ce_idx'),
        ),
    ]
