# Generated by Django 5.1.4 on 2026-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0028_alter_hirerequest_status_alter_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
