# Generated by Django 5.1.4 on 2026-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0029_jobpost_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerhistory',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careerhistory',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
