# Generated by Django 5.1.4 on 2026-09-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0030_alter_careerhistory_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='no_of_vacancy',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
