# Generated by Django 5.1.4 on 2026-10-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz', '0031_jobpost_no_of_vacancy'),
        ('jobbriz_institute', '0005_graduateroster_user_institute_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinteresthire',
            name='gradutate_roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_interest_roster_hires', to='jobbriz_institute.graduateroster'),
        ),
    ]
