# Generated by Django 5.1.4 on 2024-12-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wish_and_offers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='service_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wish_and_offers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('COO', 'Chief Operating Officer'), ('CIO', 'Chief Information Officer'), ('CSO', 'Chief Security Officer'), ('Other', 'Other')], max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='Nepal', max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='wish_and_offers/images')),
                ('title', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('offer_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_offers', to='events.event')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='wish_and_offers.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='wish_and_offers.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('COO', 'Chief Operating Officer'), ('CIO', 'Chief Information Officer'), ('CSO', 'Chief Security Officer'), ('Other', 'Other')], max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='Nepal', max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='wish_and_offers/images')),
                ('title', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('wish_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='events.event')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_wishes', to='wish_and_offers.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_wishes', to='wish_and_offers.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_matches', to='wish_and_offers.offer')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_matches', to='wish_and_offers.wish')),
            ],
        ),
    ]
