# Generated by Django 5.1.4 on 2024-12-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_slug'),
        ('wish_and_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='wish_and_offers.offer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='wish_and_offers.wish'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wish_and_offers.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wish_and_offers.service'),
        ),
    ]
