# Generated by Django 5.1.4 on 2024-12-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('COO', 'Chief Operating Officer'), ('CIO', 'Chief Information Officer'), ('CSO', 'Chief Security Officer'), ('Other', 'Other')], max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='Nepal', max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='wish_and_offers/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wish',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='detail_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wish_and_offers.detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='detail_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wish_and_offers.detail'),
            preserve_default=False,
        ),
    ]
