# Generated by Django 5.1.4 on 2024-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0003_match_match_percentage_offer_match_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wish',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
