# Generated by Django 5.1.4 on 2024-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0004_alter_match_match_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
