# Generated by Django 5.1.4 on 2025-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0005_alter_product_hs_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HS_CODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
