# Generated by Django 5.1.4 on 2025-01-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0006_hs_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs_code',
            name='unit',
        ),
    ]
