# Generated by Django 5.1.4 on 2025-01-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0007_remove_hs_code_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HS_CODE',
            new_name='HSCode',
        ),
    ]
