# Generated by Django 5.1.4 on 2025-01-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0008_rename_hs_code_hscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
