# Generated by Django 5.1.4 on 2025-01-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0009_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wish_and_offers.hscode'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wish_and_offers.hscode'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
