# Generated by Django 5.1.4 on 2025-01-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0010_alter_offer_product_alter_wish_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='wish_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
