# Generated by Django 5.1.4 on 2026-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0012_alter_category_description_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
