# Generated by Django 5.1.4 on 2026-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0013_alter_offer_designation_alter_wish_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
