# Generated by Django 5.1.4 on 2026-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0016_category_type_subcategory_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='hs_code_reference',
            new_name='reference',
        ),
    ]
