# Generated by Django 5.1.4 on 2026-01-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0017_rename_hs_code_reference_subcategory_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='wish_and_offers.subcategory'),
        ),
        migrations.AddField(
            model_name='wish',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_wishes', to='wish_and_offers.subcategory'),
        ),
    ]
