# Generated by Django 5.1.4 on 2026-01-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0018_offer_service_subcategory_wish_service_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='service_subcategory',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='service_subcategory',
            new_name='subcategory',
        ),
    ]
