# Generated by Django 5.1.4 on 2026-01-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0021_remove_service_category_service_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
