# Generated by Django 5.1.4 on 2026-01-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0023_offer_user_wish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wish_and_offers.wish'),
        ),
        migrations.AddField(
            model_name='wish',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wish_and_offers.offer'),
        ),
    ]
