# Generated by Django 5.1.4 on 2026-02-19 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_status'),
        ('wish_and_offers', '0026_alter_subcategory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], db_index=True, default='Product', max_length=10),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='wish',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], db_index=True, default='Product', max_length=10),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'type', '-created_at'], name='wish_and_of_status_84115a_idx'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['status', 'type', '-created_at'], name='wish_and_of_status_19c3dc_idx'),
        ),
    ]
