# Generated by Django 5.1.4 on 2026-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0027_alter_category_type_alter_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wish',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
