# Generated by Django 5.1.4 on 2024-12-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='business_registration.informationcategory'),
            preserve_default=False,
        ),
    ]
