# Generated by Django 5.1.4 on 2026-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Employer', 'Employer'), ('Job Seeker', 'Job Seeker'), ('Wisher', 'Wisher'), ('Offerer', 'Offerer')], max_length=10, null=True),
        ),
    ]
