# Generated by Django 5.1.4 on 2026-02-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_has_institute_customuser_institute'),
        ('jobbriz_institute', '0003_alter_graduateroster_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobbriz_institute.institute'),
        ),
    ]
