# Generated by Django 5.1.4 on 2026-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institute',
        ),
    ]
