# Generated by Django 5.1.4 on 2024-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsservice',
            name='finance_services',
            field=models.CharField(blank=True, choices=[('Meet your VCs', 'Meet your VCs'), ('Meet your Banks', 'Meet your Banks')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bdsservice',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='bds_service.tags'),
        ),
    ]
