# Generated by Django 5.1.4 on 2024-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds_service', '0002_alter_bdsservice_finance_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsservice',
            name='tags',
            field=models.ManyToManyField(to='bds_service.tags'),
        ),
    ]
