# Generated by Django 5.1.4 on 2025-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
