# Generated by Django 5.1.4 on 2025-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_session_runningsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='question',
        ),
        migrations.AddField(
            model_name='session',
            name='question',
            field=models.ManyToManyField(to='voting.question'),
        ),
    ]
