# Generated by Django 5.1.4 on 2025-01-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_rename_question_session_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='questions',
            field=models.ManyToManyField(blank=True, to='voting.question'),
        ),
    ]
