# Generated by Django 5.1.4 on 2025-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_session_is_acepting_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_acepting_questions',
            field=models.BooleanField(default=True),
        ),
    ]
