# Generated by Django 5.1.4 on 2024-12-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfIndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IssueSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.issuecategory')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfIndustrySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrycategory')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfIndustrySubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name_of_company', models.CharField(max_length=255)),
                ('address_province', models.CharField(max_length=255)),
                ('address_district', models.CharField(max_length=255)),
                ('address_municipality', models.CharField(max_length=255)),
                ('address_ward', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_designation', models.CharField(max_length=255)),
                ('contact_alternate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_of_CIM', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.issuesubcategory')),
                ('nature_of_industry_sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubsubcategory')),
            ],
        ),
    ]
