# Generated by Django 5.1.4 on 2024-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_clinic',
            name='progress_status',
            field=models.CharField(choices=[('Issue Registere and dicumented', 'Issue Registere and dicumented'), ('Issue under desk study', 'Issue under desk study'), ('Issue forwarded to concern department', 'Issue forwarded to concern department'), ('Issue solve', 'Issue solve')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
