# Generated by Django 5.1.4 on 2024-12-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0002_business_clinic_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_clinic',
            name='nature_of_industry_sub_sub_category',
        ),
        migrations.AddField(
            model_name='business_clinic',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NatureOfIndustrySubSubCategory',
        ),
    ]
