# Generated by Django 5.1.4 on 2024-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0003_remove_business_clinic_nature_of_industry_sub_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_clinic',
            name='member_of_CIM',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
