# Generated by Django 5.1.4 on 2024-12-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0004_alter_business_clinic_member_of_cim'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_clinic',
            name='issue_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.issuecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business_clinic',
            name='nature_of_industry_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrycategory'),
            preserve_default=False,
        ),
    ]
