# Generated by Django 5.1.4 on 2024-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0005_business_clinic_issue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_clinic',
            name='progress_status',
            field=models.CharField(choices=[('Issue Registere and documented', 'Issue Registere and documented'), ('Issue under desk study', 'Issue under desk study'), ('Issue forwarded to concern department', 'Issue forwarded to concern department'), ('Issue solve', 'Issue solve')], max_length=255),
        ),
    ]
