# Generated by Django 5.1.4 on 2024-12-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0007_business_clinic_is_capacity_scaleup_needed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_Clinic',
            new_name='Issue',
        ),
    ]
