# Generated by Django 5.1.4 on 2025-01-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0009_alter_issue_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_category',
        ),
        migrations.RemoveField(
            model_name='issuesubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_sub_category',
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='natureofindustrycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Nature of Industry Categories'},
        ),
        migrations.AlterModelOptions(
            name='natureofindustrysubcategory',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'Nature of Industry Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_capacity_scaleup_needed',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_common_issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_implementation_level',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_industry_specific',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_policy_level',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_procedural_hurdle',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_specific_policy_related',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default='', verbose_name='Issue Description'),
        ),
        migrations.AddField(
            model_name='issue',
            name='implementation_level_policy_level_or_capacity_scale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='industry_size',
            field=models.CharField(choices=[('Startup', 'Startup'), ('Micro', 'Micro'), ('Cottage', 'Cottage'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='industry_specific_or_common_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='nature_of_issue',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Human Resources – Labour', 'Human Resources – Labour'), ('Tax & Revenue', 'Tax & Revenue'), ('Bank & Finance', 'Bank & Finance'), ('Export', 'Export'), ('Import Substitution & Domestic Product Promotion', 'Import Substitution & Domestic Product Promotion'), ('Transport & Transit', 'Transport & Transit'), ('Local Government', 'Local Government'), ('Provincial Government', 'Provincial Government'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='policy_related_or_procedural_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='', help_text='Brief title of the issue', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_municipality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_ward',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_designation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='member_of_CIM',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name_of_company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrycategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='progress_status',
            field=models.CharField(choices=[('Issue Registered and Documented', 'Issue Registered and Documented'), ('Issue Under Desk Study', 'Issue Under Desk Study'), ('Issue Forwarded to Concerned Department', 'Issue Forwarded to Concerned Department'), ('Issue Solved', 'Issue Solved'), ('Issue Rejected', 'Issue Rejected')], default='Issue Registered and Documented', max_length=50),
        ),
        migrations.AlterField(
            model_name='natureofindustrysubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='business_clinic.natureofindustrycategory'),
        ),
        migrations.DeleteModel(
            name='IssueCategory',
        ),
        migrations.DeleteModel(
            name='IssueSubCategory',
        ),
    ]
