# Generated by Django 5.1.4 on 2025-01-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0011_issueaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='implementation_level_policy_level_or_capacity_scale',
        ),
        migrations.AddField(
            model_name='issue',
            name='forward_to_authority',
            field=models.BooleanField(default=False, help_text='Forward this issue to concerned authority'),
        ),
        migrations.AddField(
            model_name='issue',
            name='implementation_level',
            field=models.CharField(choices=[('Policy Level', 'Policy Level'), ('Implementation Level', 'Implementation Level'), ('Capacity Scale Up', 'Capacity Scale Up')], default='Implementation Level', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='share_contact_details',
            field=models.BooleanField(default=False, help_text='Allow sharing contact details with concerned authorities'),
        ),
    ]
