# Generated by Django 5.1.4 on 2025-01-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0012_remove_issue_implementation_level_policy_level_or_capacity_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='address_district',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_municipality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_province',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address_ward',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='implementation_level',
            field=models.CharField(blank=True, choices=[('Policy Level', 'Policy Level'), ('Implementation Level', 'Implementation Level'), ('Capacity Scale Up', 'Capacity Scale Up')], default='Implementation Level', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='industry_size',
            field=models.CharField(blank=True, choices=[('Startup', 'Startup'), ('Micro', 'Micro'), ('Cottage', 'Cottage'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.FileField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name_of_company',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrycategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_issue',
            field=models.CharField(blank=True, choices=[('Energy', 'Energy'), ('Human Resources – Labour', 'Human Resources – Labour'), ('Tax & Revenue', 'Tax & Revenue'), ('Bank & Finance', 'Bank & Finance'), ('Export', 'Export'), ('Import Substitution & Domestic Product Promotion', 'Import Substitution & Domestic Product Promotion'), ('Transport & Transit', 'Transport & Transit'), ('Local Government', 'Local Government'), ('Provincial Government', 'Provincial Government'), ('Other', 'Other')], default='Other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('Issue Registered and Documented', 'Issue Registered and Documented'), ('Issue Under Desk Study', 'Issue Under Desk Study'), ('Issue Forwarded to Concerned Department', 'Issue Forwarded to Concerned Department'), ('Issue Solved', 'Issue Solved'), ('Issue Rejected', 'Issue Rejected')], default='Issue Registered and Documented', max_length=50, null=True),
        ),
    ]
