# Generated by Django 5.1.4 on 2025-01-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0015_alter_issue_nature_of_industry_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrycategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory'),
        ),
    ]
