# Generated by Django 5.1.4 on 2025-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0017_alter_issue_nature_of_industry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueaction',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issueaction',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('assignment', 'Assignment'), ('forward_to_authority', 'Forward to Authority'), ('implementation_level_change', 'Implementation Level Change'), ('share_contact_change', 'Share Contact Change'), ('forward_authority_change', 'Forward Authority Change'), ('industry_category_change', 'Industry Category Change'), ('industry_subcategory_change', 'Industry Subcategory Change'), ('nature_of_issue_change', 'Nature of Issue Change')], max_length=50),
        ),
    ]
