# Generated by Django 5.1.4 on 2025-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0018_issueaction_new_value_issueaction_old_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueaction',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('implementation_level_change', 'Implementation Level Change'), ('industry_category_change', 'Industry Category Change'), ('industry_subcategory_change', 'Industry Subcategory Change'), ('nature_of_issue_change', 'Nature of Issue Change'), ('industry_size_change', 'Industry Size Change')], max_length=50),
        ),
    ]
