# Generated by Django 5.1.4 on 2026-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stall_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorbooking',
            name='stall_type',
            field=models.CharField(choices=[('Title Partner', 'Title Partner'), ('Powered By Partner', 'Powered By Partner'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=200),
        ),
    ]
