# Generated by Django 5.1.4 on 2025-03-17 09:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('max_participants', models.IntegerField(default=0)),
                ('current_participants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('venue', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('time_slots', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('Single Person', 'Single Person'), ('Group', 'Group'), ('Expo Access', 'Expo Access')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('group_members', models.JSONField(blank=True, null=True)),
                ('qualification', models.CharField(choices=[('Under SEE', 'Under SEE'), ('10+2', '10+2'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('total_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('Nabil Bank', 'Nabil Bank')], max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('agreed_to_no_refund', models.BooleanField(default=False)),
                ('is_early_bird', models.BooleanField(default=False)),
                ('is_expo_access', models.BooleanField(default=False)),
                ('is_free_entry', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_attended', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rojgar_pavillion.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_instances', to='rojgar_pavillion.topic'),
        ),
    ]
