# Generated by Django 5.1.4 on 2024-12-12 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfIndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfIndustrySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrycategory')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfIndustrySubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrysubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MeroDeshMeraiUtpadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=255)),
                ('address_province', models.CharField(max_length=255)),
                ('address_district', models.CharField(max_length=255)),
                ('address_municipality', models.CharField(max_length=255)),
                ('address_ward', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_designation', models.CharField(max_length=255)),
                ('contact_alternate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_market', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Both', 'Both')], max_length=255)),
                ('raw_material', models.CharField(choices=[('Local', 'Local'), ('International', 'International'), ('Both', 'Both')], max_length=255)),
                ('member_of_cim', models.BooleanField(default=False)),
                ('know_about_mdmu', models.BooleanField(default=False)),
                ('already_used_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('interested_in_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('self_declaration', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature_of_industry_sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrysubsubcategory')),
            ],
        ),
    ]
