# Generated by Django 5.1.4 on 2024-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='self_declaration',
            field=models.BooleanField(default=False),
        ),
    ]
