# Generated by Django 5.1.4 on 2024-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0002_alter_merodeshmeraiutpadan_self_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='know_about_mdmu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='member_of_cim',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
