# Generated by Django 5.1.4 on 2024-12-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0003_alter_merodeshmeraiutpadan_know_about_mdmu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_sub_sub_category',
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrysubcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NatureOfIndustrySubSubCategory',
        ),
    ]
