# Generated by Django 5.1.4 on 2024-12-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_clinic', '0004_alter_business_clinic_member_of_cim'),
        ('mero_desh_merai_utpadan', '0004_remove_merodeshmeraiutpadan_nature_of_industry_sub_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_clinic.natureofindustrysubcategory'),
        ),
    ]
