# Generated by Django 5.1.4 on 2024-12-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0005_alter_merodeshmeraiutpadan_nature_of_industry_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrysubcategory'),
        ),
    ]
