# Generated by Django 5.1.4 on 2025-01-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0006_merodeshmeraiutpadan_nature_of_industry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='is_It_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='is_agro_NTFPs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='is_hotel_and_other_service_industries',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='is_other_manufacturing_industries',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='is_others',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
