# Generated by Django 5.1.4 on 2025-01-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0007_merodeshmeraiutpadan_is_it_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='is_It_service',
        ),
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='is_agro_NTFPs',
        ),
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='is_hotel_and_other_service_industries',
        ),
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='is_other_manufacturing_industries',
        ),
        migrations.RemoveField(
            model_name='merodeshmeraiutpadan',
            name='is_others',
        ),
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='industry_size',
            field=models.CharField(choices=[('Startup', 'Startup'), ('Micro', 'Micro'), ('Cottage', 'Cottage'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Others', 'Others')], default='Others', max_length=255),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrycategory'),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='nature_of_industry_sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.natureofindustrysubcategory'),
        ),
    ]
