# Generated by Django 5.1.4 on 2025-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0008_remove_merodeshmeraiutpadan_is_it_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
