# Generated by Django 5.1.4 on 2025-01-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0010_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='industry_size',
            field=models.CharField(choices=[('Startup', 'Startup'), ('Micro', 'Micro'), ('Cottage', 'Cottage'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Others', max_length=255),
        ),
    ]
