# Generated by Django 5.1.4 on 2026-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0045_alter_merodeshmeraiutpadan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(upload_to='mdmu_company_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
