# Generated by Django 5.1.4 on 2026-01-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0047_alter_merodeshmeraiutpadan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='merodeshmeraiutpadan',
            name='company_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mero_desh_merai_utpadan.companylogo'),
        ),
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
