# Generated by Django 5.1.4 on 2026-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero_desh_merai_utpadan', '0088_alter_merodeshmeraiutpadan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merodeshmeraiutpadan',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
