# Generated by Django 5.1.4 on 2026-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Co-working Seat', 'Co-working Seat'), ('Private Room', 'Private Room')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('founder_name', models.CharField(max_length=255)),
                ('founder_designation', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('no_of_seats', models.IntegerField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_category', models.CharField(blank=True, choices=[('The Big Brain Room', 'The Big Brain Room'), ('The Grind Garage', 'The Grind Garage'), ('The Fusion Lab', 'The Fusion Lab')], max_length=100, null=True)),
                ('no_of_participants', models.IntegerField(blank=True, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('photocopy', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('interactive_board', models.BooleanField(default=False)),
                ('whiteboard_marker', models.BooleanField(default=False)),
                ('tea_coffee_water', models.BooleanField(default=False)),
                ('other_service', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('old_booking_date', models.DateField()),
                ('new_booking_date', models.DateField()),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('old_room_category', models.CharField(blank=True, choices=[('The Big Brain Room', 'The Big Brain Room'), ('The Grind Garage', 'The Grind Garage'), ('The Fusion Lab', 'The Fusion Lab')], max_length=100, null=True)),
                ('new_room_category', models.CharField(blank=True, choices=[('The Big Brain Room', 'The Big Brain Room'), ('The Grind Garage', 'The Grind Garage'), ('The Fusion Lab', 'The Fusion Lab')], max_length=100, null=True)),
                ('old_booking_type', models.CharField(blank=True, choices=[('Co-working Seat', 'Co-working Seat'), ('Private Room', 'Private Room')], max_length=100, null=True)),
                ('new_booking_type', models.CharField(blank=True, choices=[('Co-working Seat', 'Co-working Seat'), ('Private Room', 'Private Room')], max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
