# Generated by Django 5.1.4 on 2026-02-18 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incubationcenter',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='incubationcenter',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='old_booking_date',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='old_booking_type',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='old_room_category',
        ),
        migrations.AddField(
            model_name='incubationcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incubationcenter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubationcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='incubation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='incubation_center.incubationcenter'),
        ),
        migrations.AlterField(
            model_name='incubationcenter',
            name='founder_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incubationcenter',
            name='founder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
