# Generated by Django 5.1.4 on 2026-02-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_center', '0002_rename_company_name_incubationcenter_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reschedulerequest',
            old_name='incubation_center',
            new_name='booking',
        ),
    ]
