# Generated by Django 5.1.4 on 2026-02-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_type', models.CharField(choices=[('Technical School', 'Technical School'), ('Polytechnic', 'Polytechnic'), ('Training Centre', 'Training Centre'), ('College', 'College')], max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institute_logos/')),
                ('primary_contact_person', models.CharField(max_length=100)),
                ('primary_contact_person_phone', models.CharField(max_length=15)),
                ('primary_contact_person_email', models.EmailField(max_length=254)),
                ('primary_contact_person_designation', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('permanent_province', models.CharField(max_length=255)),
                ('permanent_district', models.CharField(max_length=255)),
                ('permanent_municipality', models.CharField(max_length=255)),
                ('permanent_ward', models.CharField(max_length=255)),
                ('current_province', models.CharField(blank=True, max_length=255, null=True)),
                ('current_district', models.CharField(blank=True, max_length=255, null=True)),
                ('current_municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('current_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('level_completed', models.CharField(blank=True, choices=[('Pre-Diploma', 'Pre-Diploma'), ('Diploma', 'Diploma'), ('TSLC', 'TSLC'), ('Short Course', 'Short Course'), ('Bachelor', 'Bachelor'), ('Other', 'Other')], max_length=50, null=True)),
                ('subject_trade_stream', models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('IT', 'IT'), ('Hotel Mgmt', 'Hotel Management'), ('ECD', 'Early Childhood Development'), ('Tea Tech', 'Tea Technology'), ('Electronic', 'Electronic'), ('Other', 'Other')], max_length=100, null=True)),
                ('specialization_key_skills', models.TextField(blank=True, null=True)),
                ('passed_year', models.IntegerField(blank=True, null=True)),
                ('certifying_agency', models.CharField(blank=True, choices=[('CTEVT', 'CTEVT'), ('University', 'University'), ('Other', 'Other')], max_length=100, null=True)),
                ('certifying_agency_name', models.CharField(blank=True, help_text='Write the Name if Other', max_length=255, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_status', models.CharField(choices=[('Available for Job', 'Available for Job'), ('Not Available', 'Not Available')], default='Available for Job', max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbriz_institute.institute')),
            ],
        ),
    ]
