# Generated by Django 5.1.4 on 2026-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz_institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateroster',
            name='subject_trade_stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
