# Generated by Django 5.1.4 on 2026-02-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz_institute', '0002_alter_graduateroster_subject_trade_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateroster',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobbriz_institute.institute'),
        ),
    ]
