# Generated by Django 5.1.4 on 2026-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbriz_institute', '0003_alter_graduateroster_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateroster',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='graduateroster',
            name='roster_type',
            field=models.CharField(blank=True, choices=[('Roster-Graduates', 'Roster-Graduates'), ('Individual', 'Individual')], max_length=50, null=True),
        ),
    ]
