# Generated by Django 5.1.4 on 2026-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceZoneBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CIM Member', 'CIM Member'), ('Startup', 'Startup & Innovative Products'), ('Women Entrepreneur', 'Women Entrepreneur'), ('Others', 'Other priority areas')], max_length=50)),
                ('preferred_month', models.DateField(help_text='First day of the month for which booking is requested')),
                ('description', models.TextField(help_text='Details about products, innovations, or skills to be displayed')),
                ('willing_to_cooperate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waitlisted', 'Waitlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience Zone Booking',
                'verbose_name_plural': 'Experience Zone Bookings',
                'ordering': ['created_at'],
            },
        ),
    ]
