# Generated by Django 5.1.4 on 2026-02-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencezonebooking',
            name='willing_to_cooperate',
        ),
    ]
