# Generated by Django 5.1.4 on 2026-02-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_zone', '0002_remove_experiencezonebooking_willing_to_cooperate'),
        ('wish_and_offers', '0026_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencezonebooking',
            name='category',
        ),
        migrations.AddField(
            model_name='experiencezonebooking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_zone_hscode', to='wish_and_offers.hscode'),
        ),
        migrations.AddField(
            model_name='experiencezonebooking',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_zone_subcategories', to='wish_and_offers.subcategory'),
        ),
        migrations.AddField(
            model_name='experiencezonebooking',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experiencezonebooking',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=10),
        ),
        migrations.AlterField(
            model_name='experiencezonebooking',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experiencezonebooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
