# Generated by Django 5.1.4 on 2026-02-11 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_zone', '0003_remove_experiencezonebooking_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencezonebooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
