# Generated by Django 5.1.4 on 2026-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_zone', '0004_alter_experiencezonebooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencezonebooking',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='experience_zone/logo'),
        ),
    ]
